### ISSUE TITLE
Model the SQL generation in sqldb.cc as an SQL ast before generating raw SQL.

### ISSUE THREAD

**Issue by panyam** [kaladron/galactic-bloodshed#9]
Currently for each of the CRUD operations on the SQLStore class, I am hand crafting SQL from the inputs.  An intermediate SQL AST would be cleaner and also help with better testing.  A lot easier and reliable to compare ASTs instead of comparing the generated SQL.

**Comment by kaladron** [comment]
Taking a different approach to persistent storage.
